version: '3.7'

services:
  reverseproxy:
    build:
      context: .
      dockerfile: nginx/nginx.Dockerfile
    depends_on:
      - globomatics.identityserver
    ports:
      - "5200:5100"

  globomantics.identityserver:
    image: ${DOCKER_REGISTRY-}globomanticsidentityserver
    build:
      context: .
      dockerfile: Globomantics.IdentityServer/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://*:5500
    ports:
      - "5000:5500"